- lib/createForm.js
- package.json
- test/lib.spec.js
Fixes the https://github.com/tjinauyeung/svelte-forms-lib/issues/8 — broken integration with checkbox inputs.
> Fix broken checkbox

- lib/createForm.js
- package-lock.json
- package.json
- test/lib.spec.js
With those two functions you can manage the update of the form data without input events and you can validate a value by field name.
This PR can close #21 and #1 (you don't need to wrap a custom event for the handleChange function).
> UpdateValidateField and validateField functions

- LICENCE
@tjinauyeung not sure what protocol you'd like for PRs, but since your name is in this licence I thought I'd add you as a reviewer.
> docs(licence): add MIT licence - closes #32

- .travis.yml
this config will need to be expanded once semantic-release is added
> ci(travis): add basic config

- package-lock.json
- package.json
> fix(package.json): install svelte as a dev dep

- .github/ISSUE_TEMPLATE/bug_report.md
- lib/create-form.js
- lib/util.js
Re-opening a new PR since pull bot closed down #39 and I've deleted the previous repo.
Updated template to use `|preventDefault` as @larrybotha suggested.
> docs(bug_report.md): update steps to reproduce section of bug report

- lib/create-form.js
- lib/util.js
- test/lib.spec.js
> Add support for nullish value returned from validate

- lib/create-form.js
- test/lib.spec.js
> Validate field value with yup validateAt

- lib/components/Form.svelte
> Only pass unused props on to form element

- test/lib.spec.js
> fix(lib.spec.js): fix async updates resulting in false positives in test runs

- lib/create-form.js
- lib/util.js
- package-lock.json
- package.json
- test/library.spec.js
> fix(create-form): use deep equal to determine if  initial values are modified

- lib/util.js
- package-lock.json
- package.json
> feat(utils): replace lodash.isequal with smaller dequal dep

- lib/index.js
fix #85
EDIT: addresses a request for exporting key in #13
> feat(component context): export key

- lib/index.d.ts
- lib/svelte-jsx.d.ts
there where some bugs with the provided type definitions, i also included svelte-jsx from
language-tools to provide restProps typedefinitions for field/textarea elements etc.
> fix(index.d.ts): fix some type definitions and improvements

- lib/components/Form.svelte
- test/config/jest.test.js
- test/specs/components/fixtures/input.svelte
- test/specs/components/form.spec.js
- test/specs/components/textarea.spec.js
- test/specs/library.spec.js
> feat(form component): expose createForm methods via slot props

- husky.config.js
- package-lock.json
- package.json
> chore(packages): install svelte-check

- .github/ISSUE_TEMPLATE/bug_report.md
Use GitLab's bug report template as a basis for this template.
See https://gitlab.com/gitlab-org/gitlab/-/blob/master/.gitlab/issue_templates/Bug.md
> chore(bug report template): improve template

- .github/ISSUE_TEMPLATE/feature_request.md
Use GitLab's feature template as a basis:
https://gitlab.com/gitlab-org/gitlab/-/blob/master/.gitlab/issue_templates/Feature%20proposal.md
> chore(feature request template): improve template

- package.json
- rollup.config.js
see https://docs.skypack.dev/package-authors/package-checks
> feat(package.json): add exports property

- lib/components/ErrorMessage.svelte
- lib/components/Field.svelte
- lib/components/Form.svelte
- lib/components/Select.svelte
- lib/components/Textarea.svelte
- package.json
- rollup.config.js
> fix(package.json): revert exports feature

- lib/util.js
- test/specs/library.spec.js
> fix(isvalid store): fix isValid returning 'false' for valid nested arrays

- lib/create-form.js
- lib/util.js
- package-lock.json
- test/specs/library.spec.js
This fixed my issue reported here #125 
After trying it out, it seems to work as expected.
> fix: Validation fails if validation schema contains objects that contain properties

- lib/util.js
Reverts tjinauyeung/svelte-forms-lib#131
> Revert "Empty object in errors when field is array type"

- .eslintrc.js
- lib/util.js
- test/specs/library.spec.js
> test(spec): add tests for validating array errors

- lib/index.d.ts
> fix(index.d.ts): add missing parameter types to function signatures
